#!/bin/sh
stty -F /dev/ttyS0 115200 raw
#/root/tester_verification/run_verification
echo "../iob_soc_sut_mem.config"
rz
# Script to verify linux functioning
echo "Test passed!" > /tmp/test.log
# Send file via UART with Zmodem
sz -e /tmp/test.log
