#!/bin/sh

# Load Linux Kernel Modules
insmod /drivers/iob_timer.ko
insmod /drivers/iob_soc_sut.ko
insmod /drivers/iob_gpio.ko
insmod /drivers/iob_pfsm.ko
insmod /drivers/iob_ila.ko

# Set correct settings for uart port connected to SUT
stty -F /dev/ttyS0 115200 raw -echo -echoe -echok

# Run verification program
/root/tester_verification/run_verification
